# Generated by Django 4.1.3 on 2022-11-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_post_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_color',
            field=models.CharField(choices=[('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('purple', 'purple'), ('pink', 'pink')], default='white', max_length=75),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.post'),
        ),
    ]
