# Generated by Django 4.1.3 on 2022-11-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_account_post_color_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/var/www/replacement-twitter/account-static'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/var/www/replacement-twitter/account-static'),
        ),
    ]
