# Generated by Django 4.1.3 on 2022-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_post_image_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/var/www/replacement-twitter/account-static'),
        ),
    ]
