# Generated by Django 4.1.3 on 2022-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_account_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='background_photo',
            field=models.FilePathField(blank=True, max_length=250, null=True, path='/var/www/replacement-twitter/account-static'),
        ),
    ]
