# Generated by Django 4.1.3 on 2022-11-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_account_background_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_post', to='backend.account'),
        ),
    ]
