# Generated by Django 4.1.3 on 2022-11-28 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_post_post_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='/var/www/replacement-twitter/account-static'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_video',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='backend.account')),
                ('likes', models.ManyToManyField(blank=True, related_name='messages_liked', to='backend.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.account')),
            ],
        ),
    ]
