# Generated by Django 4.1.3 on 2022-12-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_attachment_file_path_remove_attachment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='background_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_background_photo', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_profile_photo', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='backend.attachment'),
        ),
    ]
