# Generated by Django 4.1.3 on 2022-12-10 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_message_image_alter_account_background_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 4, 10, 17, 645858)),
        ),
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 4, 10, 17, 645590)),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 4, 10, 17, 648506)),
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 4, 10, 17, 647720)),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 4, 10, 17, 646726)),
        ),
    ]
