# Generated by Django 4.1.3 on 2022-12-09 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_message_image_alter_account_background_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 4, 33, 10, 691406)),
        ),
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 4, 33, 10, 691102)),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 4, 33, 10, 694018)),
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 4, 33, 10, 693153)),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 12, 9, 4, 33, 10, 692348)),
        ),
    ]
