# Generated by Django 4.1.3 on 2022-12-10 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_account_created_attachment_created_comment_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_video', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 303283)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 302789)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 310049)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 306720)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 304865)),
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 12, 10, 21, 22, 1, 308343))),
                ('name', models.CharField(default='ChatRoom', max_length=100)),
                ('accounts', models.ManyToManyField(blank=True, related_name='chatroom_accounts', to='backend.account')),
                ('messages', models.ManyToManyField(blank=True, related_name='chatroom_messages', to='backend.message')),
            ],
        ),
    ]
