# Generated by Django 4.1.3 on 2022-12-10 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_message_video_alter_account_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_account',
        ),
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_messages', to='backend.chatroom'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 346252)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 345992)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 348910)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 349974)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 348022)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 17, 43, 347111)),
        ),
    ]
