# Generated by Django 4.1.3 on 2022-12-10 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_message_to_account_message_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 2547)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 2282)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 5271)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 6342)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 4354)),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_video', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 22, 28, 27, 3418)),
        ),
    ]
