# Generated by Django 4.1.3 on 2022-12-11 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_account_created_alter_attachment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_background_photo', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 546300)),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_profile_photo', to='backend.attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 546014)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 548896)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 549949)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 548025)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 21, 12, 6, 547212)),
        ),
    ]
