# Generated by Django 4.1.3 on 2023-01-15 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_account_background_photo_alter_account_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ext',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
