apt-get update;
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -;
apt install -y nodejs;
apt-get install -y nginx vim uwsgi;
apt-get install -y uwsgi-plugin-python3;
apt-get install -y python3.8-venv;
python3 -m venv /var/www/replacement-twitter/venv;
apt-get install -y python3-pip;
cd /var/www/replacement-twitter;
touch db.sqlite3;
source venv/bin/activate;
pip install -r requirements.txt;
python3 manage.py migrate;
cp /var/www/replacement-twitter/Deployment/nginx.conf /etc/nginx/sites-enabled/default;
cp /var/www/replacement-twitter/Deployment/uwsgi.ini /etc/uwsgi/apps-enabled/replacement-twitter.ini;
mkdir /var/log/replacement-twitter;
cd /var/www/replacement-twitter/frontend;
npm install -g npm@latest;
npm install;
npm install -g @quasar/cli;
quasar build;
cd /var/www/replacement-twitter;
python3 manage.py collectstatic;
service uwsgi restart;
service nginx restart;
